#server:
#  address: 0.0.0.0
#  port: 7777
#  application:
#    name: pls-outqry
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.echo.outqry.entity
#  mapper-locations: classpath:mapper/*.xml
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:mm:test
#    username: forrest
#    password: 12345
#    schema: classpath:schema-h2.sql
#    hikari:
#      maximum-pool-size:
#    dbcp2:
#      driver: com.h2.Driver
